require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ColorLogosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ColorLogo. As you add validations to ColorLogo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ColorLogosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all color_logos as @color_logos" do
      color_logo = ColorLogo.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:color_logos)).to eq([color_logo])
    end
  end

  describe "GET #show" do
    it "assigns the requested color_logo as @color_logo" do
      color_logo = ColorLogo.create! valid_attributes
      get :show, {:id => color_logo.to_param}, valid_session
      expect(assigns(:color_logo)).to eq(color_logo)
    end
  end

  describe "GET #new" do
    it "assigns a new color_logo as @color_logo" do
      get :new, {}, valid_session
      expect(assigns(:color_logo)).to be_a_new(ColorLogo)
    end
  end

  describe "GET #edit" do
    it "assigns the requested color_logo as @color_logo" do
      color_logo = ColorLogo.create! valid_attributes
      get :edit, {:id => color_logo.to_param}, valid_session
      expect(assigns(:color_logo)).to eq(color_logo)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ColorLogo" do
        expect {
          post :create, {:color_logo => valid_attributes}, valid_session
        }.to change(ColorLogo, :count).by(1)
      end

      it "assigns a newly created color_logo as @color_logo" do
        post :create, {:color_logo => valid_attributes}, valid_session
        expect(assigns(:color_logo)).to be_a(ColorLogo)
        expect(assigns(:color_logo)).to be_persisted
      end

      it "redirects to the created color_logo" do
        post :create, {:color_logo => valid_attributes}, valid_session
        expect(response).to redirect_to(ColorLogo.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved color_logo as @color_logo" do
        post :create, {:color_logo => invalid_attributes}, valid_session
        expect(assigns(:color_logo)).to be_a_new(ColorLogo)
      end

      it "re-renders the 'new' template" do
        post :create, {:color_logo => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested color_logo" do
        color_logo = ColorLogo.create! valid_attributes
        put :update, {:id => color_logo.to_param, :color_logo => new_attributes}, valid_session
        color_logo.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested color_logo as @color_logo" do
        color_logo = ColorLogo.create! valid_attributes
        put :update, {:id => color_logo.to_param, :color_logo => valid_attributes}, valid_session
        expect(assigns(:color_logo)).to eq(color_logo)
      end

      it "redirects to the color_logo" do
        color_logo = ColorLogo.create! valid_attributes
        put :update, {:id => color_logo.to_param, :color_logo => valid_attributes}, valid_session
        expect(response).to redirect_to(color_logo)
      end
    end

    context "with invalid params" do
      it "assigns the color_logo as @color_logo" do
        color_logo = ColorLogo.create! valid_attributes
        put :update, {:id => color_logo.to_param, :color_logo => invalid_attributes}, valid_session
        expect(assigns(:color_logo)).to eq(color_logo)
      end

      it "re-renders the 'edit' template" do
        color_logo = ColorLogo.create! valid_attributes
        put :update, {:id => color_logo.to_param, :color_logo => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested color_logo" do
      color_logo = ColorLogo.create! valid_attributes
      expect {
        delete :destroy, {:id => color_logo.to_param}, valid_session
      }.to change(ColorLogo, :count).by(-1)
    end

    it "redirects to the color_logos list" do
      color_logo = ColorLogo.create! valid_attributes
      delete :destroy, {:id => color_logo.to_param}, valid_session
      expect(response).to redirect_to(color_logos_url)
    end
  end

end
