require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DefaultEmailTemplatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DefaultEmailTemplate. As you add validations to DefaultEmailTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DefaultEmailTemplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all default_email_templates as @default_email_templates" do
      default_email_template = DefaultEmailTemplate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:default_email_templates)).to eq([default_email_template])
    end
  end

  describe "GET #show" do
    it "assigns the requested default_email_template as @default_email_template" do
      default_email_template = DefaultEmailTemplate.create! valid_attributes
      get :show, {:id => default_email_template.to_param}, valid_session
      expect(assigns(:default_email_template)).to eq(default_email_template)
    end
  end

  describe "GET #new" do
    it "assigns a new default_email_template as @default_email_template" do
      get :new, {}, valid_session
      expect(assigns(:default_email_template)).to be_a_new(DefaultEmailTemplate)
    end
  end

  describe "GET #edit" do
    it "assigns the requested default_email_template as @default_email_template" do
      default_email_template = DefaultEmailTemplate.create! valid_attributes
      get :edit, {:id => default_email_template.to_param}, valid_session
      expect(assigns(:default_email_template)).to eq(default_email_template)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DefaultEmailTemplate" do
        expect {
          post :create, {:default_email_template => valid_attributes}, valid_session
        }.to change(DefaultEmailTemplate, :count).by(1)
      end

      it "assigns a newly created default_email_template as @default_email_template" do
        post :create, {:default_email_template => valid_attributes}, valid_session
        expect(assigns(:default_email_template)).to be_a(DefaultEmailTemplate)
        expect(assigns(:default_email_template)).to be_persisted
      end

      it "redirects to the created default_email_template" do
        post :create, {:default_email_template => valid_attributes}, valid_session
        expect(response).to redirect_to(DefaultEmailTemplate.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved default_email_template as @default_email_template" do
        post :create, {:default_email_template => invalid_attributes}, valid_session
        expect(assigns(:default_email_template)).to be_a_new(DefaultEmailTemplate)
      end

      it "re-renders the 'new' template" do
        post :create, {:default_email_template => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested default_email_template" do
        default_email_template = DefaultEmailTemplate.create! valid_attributes
        put :update, {:id => default_email_template.to_param, :default_email_template => new_attributes}, valid_session
        default_email_template.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested default_email_template as @default_email_template" do
        default_email_template = DefaultEmailTemplate.create! valid_attributes
        put :update, {:id => default_email_template.to_param, :default_email_template => valid_attributes}, valid_session
        expect(assigns(:default_email_template)).to eq(default_email_template)
      end

      it "redirects to the default_email_template" do
        default_email_template = DefaultEmailTemplate.create! valid_attributes
        put :update, {:id => default_email_template.to_param, :default_email_template => valid_attributes}, valid_session
        expect(response).to redirect_to(default_email_template)
      end
    end

    context "with invalid params" do
      it "assigns the default_email_template as @default_email_template" do
        default_email_template = DefaultEmailTemplate.create! valid_attributes
        put :update, {:id => default_email_template.to_param, :default_email_template => invalid_attributes}, valid_session
        expect(assigns(:default_email_template)).to eq(default_email_template)
      end

      it "re-renders the 'edit' template" do
        default_email_template = DefaultEmailTemplate.create! valid_attributes
        put :update, {:id => default_email_template.to_param, :default_email_template => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested default_email_template" do
      default_email_template = DefaultEmailTemplate.create! valid_attributes
      expect {
        delete :destroy, {:id => default_email_template.to_param}, valid_session
      }.to change(DefaultEmailTemplate, :count).by(-1)
    end

    it "redirects to the default_email_templates list" do
      default_email_template = DefaultEmailTemplate.create! valid_attributes
      delete :destroy, {:id => default_email_template.to_param}, valid_session
      expect(response).to redirect_to(default_email_templates_url)
    end
  end

end
