require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WatermarksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Watermark. As you add validations to Watermark, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WatermarksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all watermarks as @watermarks" do
      watermark = Watermark.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:watermarks)).to eq([watermark])
    end
  end

  describe "GET #show" do
    it "assigns the requested watermark as @watermark" do
      watermark = Watermark.create! valid_attributes
      get :show, {:id => watermark.to_param}, valid_session
      expect(assigns(:watermark)).to eq(watermark)
    end
  end

  describe "GET #new" do
    it "assigns a new watermark as @watermark" do
      get :new, {}, valid_session
      expect(assigns(:watermark)).to be_a_new(Watermark)
    end
  end

  describe "GET #edit" do
    it "assigns the requested watermark as @watermark" do
      watermark = Watermark.create! valid_attributes
      get :edit, {:id => watermark.to_param}, valid_session
      expect(assigns(:watermark)).to eq(watermark)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Watermark" do
        expect {
          post :create, {:watermark => valid_attributes}, valid_session
        }.to change(Watermark, :count).by(1)
      end

      it "assigns a newly created watermark as @watermark" do
        post :create, {:watermark => valid_attributes}, valid_session
        expect(assigns(:watermark)).to be_a(Watermark)
        expect(assigns(:watermark)).to be_persisted
      end

      it "redirects to the created watermark" do
        post :create, {:watermark => valid_attributes}, valid_session
        expect(response).to redirect_to(Watermark.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved watermark as @watermark" do
        post :create, {:watermark => invalid_attributes}, valid_session
        expect(assigns(:watermark)).to be_a_new(Watermark)
      end

      it "re-renders the 'new' template" do
        post :create, {:watermark => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested watermark" do
        watermark = Watermark.create! valid_attributes
        put :update, {:id => watermark.to_param, :watermark => new_attributes}, valid_session
        watermark.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested watermark as @watermark" do
        watermark = Watermark.create! valid_attributes
        put :update, {:id => watermark.to_param, :watermark => valid_attributes}, valid_session
        expect(assigns(:watermark)).to eq(watermark)
      end

      it "redirects to the watermark" do
        watermark = Watermark.create! valid_attributes
        put :update, {:id => watermark.to_param, :watermark => valid_attributes}, valid_session
        expect(response).to redirect_to(watermark)
      end
    end

    context "with invalid params" do
      it "assigns the watermark as @watermark" do
        watermark = Watermark.create! valid_attributes
        put :update, {:id => watermark.to_param, :watermark => invalid_attributes}, valid_session
        expect(assigns(:watermark)).to eq(watermark)
      end

      it "re-renders the 'edit' template" do
        watermark = Watermark.create! valid_attributes
        put :update, {:id => watermark.to_param, :watermark => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested watermark" do
      watermark = Watermark.create! valid_attributes
      expect {
        delete :destroy, {:id => watermark.to_param}, valid_session
      }.to change(Watermark, :count).by(-1)
    end

    it "redirects to the watermarks list" do
      watermark = Watermark.create! valid_attributes
      delete :destroy, {:id => watermark.to_param}, valid_session
      expect(response).to redirect_to(watermarks_url)
    end
  end

end
